spring:
  application:
    name: customer-service
  
server:
  port: 8081

# Database configuration (to be configured later)
# spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5432/customer_db
#     username: postgres
#     password: postgres

# Logging
logging:
  level:
    com.daghanemre.fintech.customer: DEBUG
